# ── Broker MQTT ──────────────────────────────
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=usine-serveur
mqtt.qos=1

# ── Topics entrants  ─────────
mqtt.topic.orders=orders/+
mqtt.topic.serials.check=serials/+/check

# ── Pool de threads de l'Usine ────────────────
usine.pool.size=10